from Inventario import *

product1=Producto("mouse",180,3)
product2 = Producto("laptop", 1200, 5)
product3 = Producto("mouse", 25, 10)
product4 = Producto("teclado", 45, 8)
product5 = Producto("monitor", 300, 4)
product6 = Producto("audifonos", 80, 12)
product7 = Producto("camara", 550, 3)
product8 = Producto("microfono", 120, 6)
product9 = Producto("escritorio", 250, 2)
product10 = Producto("silla_gamer", 350, 5)
product11 = Producto("lampara", 40, 15)
product12 = Producto("disco_duro", 100, 20)
product13 = Producto("tarjeta_video", 800, 2)
product14 = Producto("procesador", 400, 7)
product15 = Producto("memoria_ram", 90, 14)
product16 = Producto("gabinete", 110, 5)
product17 = Producto("fuente_poder", 130, 9)
product18 = Producto("ventilador", 20, 25)
product19 = Producto("impresora", 200, 4)
product20 = Producto("escaner", 150, 3)
product21 = Producto("tablet", 600, 6)
product22 = Producto("reloj_smart", 220, 11)
product23 = Producto("parlante", 95, 13)
product24 = Producto("cable_hdmi", 15, 50)
product25 = Producto("cargador", 30, 30)
product26 = Producto("mochila", 65, 18)

categoria1=Categoria("Electronicos")
categoria1.agregar_producto(product1)
categoria1.agregar_producto(product2)
categoria1.agregar_producto(product3)
categoria1.agregar_producto(product4)
categoria1.agregar_producto(product4)


categoria1.valor_total_categoria()

listaproductos=[]
listaproductos.append(product1)
listaproductos.append(product2)
listaproductos.append(product3)
listaproductos.append(product4)
listaproductos.append(product5)
listaproductos.append(product6)
listaproductos.append(product7)
listaproductos.append(product8)
listaproductos.append(product9)
listaproductos.append(product10)
listaproductos.append(product11)
listaproductos.append(product12)
listaproductos.append(product13)


pedido1=Pedido("Maria")
pedido1.agregar_producto(product13)
pedido1.agregar_producto(product11)
pedido1.agregar_producto(product7)
print(pedido1.lista_comprados)
pedido1.calcula_total()
pedido1.finalizar_pedido(listaproductos)